### ISSUE TITLE
Bug Report: default topicmap

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1029]
### Expected Behavior

Topicmap in documentation was not yet updated

### Current Behavior

It should be 

```yaml
topicmap:
    - bidirectional: false
      name: HighIntegrity
      send_direction: to_remote
      topic: ^ia\..+\..+\..+\.((addMaintenanceActivity)|(addOrder)|(addParentToChild)|(addProduct)|(addShift)|(count)|(deleteShiftByAssetIdAndBeginTimestamp)|(deleteShiftById)|(endOrder)|(modifyProducedPieces)|(modifyState)|(productTag)|(productTagString)|(recommendation)|(scrapCount)|(startOrder)|(state)|(uniqueProduct)|(scrapUniqueProduct)).+$
    - bidirectional: false
      name: HighThroughput
      send_direction: to_remote
      topic: ^ia\..+\..+\..+\.(processValue).*$
```

### Steps to Reproduce

no

### Context (Environment)

venice

### Version

v0.9.x
