### ISSUE TITLE
Add option to add custom microservices

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1169]
**Is your feature request related to a problem? Please describe.**
The United Manufacturing Hub provides an IT / OT infrastructure, therefore it should be able to provide custom microservices. Kuebrnetes is quite complex and might hinder someone in deploying microservices and then in total in using the United Manufacturing Hub.

**Describe the solution you'd like**
Add functionality to Helm Chart (allowing multiple microservices to be deployed):
```
customMicroservice:
                - hello123:
                                image: united-manufacturing-hub/custom-service:latest
                                
                                # imagePullPolicy: Always is recommended when using latest tags. Otherwise, please use IfNotPresent
                                imagePullPolicy: Always
                                
                                # these will be passed as environment variables
                                env:
                                                - name: LOGGING_LEVEL
                                                value: PRODUCTION
                                
                                # ports will expose port 80 on the host on port 8080
                                ports: "8080:80"
                                
                                # startupProbe, livenessProbe, check whether port 8080 "/health" is accessible. 
                                # If not (e.g., due to container stuck), the container will be restarted
                                # startupProbe: 100
                                # livenessProbe: 50
                                
                                # statefulEnabled will automatically mount a volume under /data, which can be used to store data. 
                                # Recommendation is to turn it off
                                statefulEnabled: true
                - test123:
                                image: ……
                                …
```
