### ISSUE TITLE
kafka-to-postgresql: Postgres not yet available: pq: database "sslmode=true" does not exist 

### ISSUE THREAD

**Issue by desertspider** [united-manufacturing-hub/united-manufacturing-hub#1406]
### Expected Behavior

I am testing kafka-to-postgresql. I get the following Error:

kafka-to-postgresql: Postgres not yet available: pq: database "sslmode=true" does not exist 

My docker compose:

```
  kafka-to-postgresql:
    image: a0aa3649a177
    restart: always
    environment:
     - DRY_RUN=false
     - KAFKA_BOOTSTRAP_SERVER=kafka:9092
     - KAFKA_LISTEN_TOPIC=^ia.+
     - POSTGRES_HOST='azuretenant.postgres.database.azure.com'
     - POSTGRES_PORT=5432
     - POSTGRES_SSLMODE=true
     - POSTGRES_USER=username
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=FACTORYINSIGHT_DATABASE
    depends_on:
     - kafka
```
POSTGRES_SSLMODE to false gives the same error, only with database sslmode=false

Clearly it uses the ssl mode als database name.

I pulled the latest code from git and compiled all the images with "compile_all_containers.sh"

If i use the Postgres 12 default docker compose database, i get errors that SSL is not enabled (even if i set SSLMODE to false)

### Current Behavior

.

### Steps to Reproduce

.

### Context (Environment)

.

### Version

not applicable
