### ISSUE TITLE
Wrong value reference in helm template

### ISSUE THREAD

**Issue by DaruZero** [united-manufacturing-hub/united-manufacturing-hub#1474]
### Expected Behavior

The PersistanceVolumeClaim template for the mqtt-broker extensions should reference the correct value from the `values.yaml` file

### Current Behavior

In the PersistanceVolumeClaim template for the mqtt-broker extensions (`/deployment/united-manufacturing-hub/templates/hivemq/pvc-extensions.yaml` the storage size request references the value for the storage PVC instead of the extension one

```yaml
  resources:
    requests:
      storage: {{.Values.mqtt_broker.persistence.storage.size}}
```

### Steps to Reproduce

Look at the template definition

### Context (Environment)

Writing the documentation

### Possible Solution

Replace with the correct value reference

```yaml
  resources:
    requests:
      storage: {{.Values.mqtt_broker.persistence.extension.size}}
```

### Version

v0.9.x

### Anything else?

Relevant `mqtt_broker` section in the `values.yaml` file:

```yaml
  persistence:
    extension:
      size: 100Mi
    storage:
      size: 2Gi
```
