### ISSUE TITLE
Implement UI for Kafka

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#724]
**Is your feature request related to a problem? Please describe.**
For debugging purposes and for easier understanding we need an UI in the stack that helps people see whats in it.

**Describe the solution you'd like**
Something like `provectuslabs/kafka-ui`

**Comment by JeremyTheocharis** [comment]
or akhq:

```yaml
affinity: {}
annotations: {}
configuration:
  akhq:
    connections:
      local:
        properties:
          bootstrap.servers: factorycube-server-kafka:9092
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
containerSecurityContext: {}
existingSecrets: ""
extraEnv: []
extraVolumeMounts: []
extraVolumes: []
image:
  repository: tchiotludo/akhq
  tag: ""
ingress:
  annotations: {}
  enabled: false
  hosts:
  - akhq.demo.com
  paths:
  - /
  tls: []
initContainers: {}
kafkaSecrets: []
labels: {}
nodeSelector: {}
podAnnotations: {}
podLabels: {}
readinessProbe:
  prefix: ""
resources: {}
secrets: {}
securityContext: {}
service:
  enabled: true
  labels: {}
  port: 8081
  type: LoadBalancer
serviceAccount:
  create: false
tolerations: []
```
