### ISSUE TITLE
minio starting althoug blob storage is disabled

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#836]
### Expected Behavior

```yaml
_000_commonConfig:
  blobstorage:
    enabled: false
```

Therefore, minio should not start

### Current Behavior

minio starts

### Steps to Reproduce

Install v0.8.0 with using development.yaml
Minio will start

### Context (Environment)

While testing v0.8.0

### Version

v0.8.x
