### ISSUE TITLE
Node-RED default flows not working

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#837]
### Expected Behavior

```yaml
_000_commonConfig:
  dataprocessing:
    nodered:
      defaultFlows: true
      enabled: true
```

Therefore, there should be default flows

### Current Behavior

There are not default flows and an error message appears

### Relevant log output

```shell
create Pod united-manufacturing-hub-nodered-0 in StatefulSet united-manufacturing-hub-nodered failed error: Pod "united-manufacturing-hub-nodered-0" is invalid: spec.initContainers[0].volumeMounts[1].name: Not found: "united-manufacturing-hub-nodered-flows"
```

### Steps to Reproduce

Set `_000_commonConfig.dataprocessing.nodered.defaultFlows=true`

### Context (Environment)

Testing v0.8.0

### Version

v0.8.x
